name: Lint and Test

on: pull_request

jobs:

  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.3"

      - name: lint and test
        run: uv run --locked -- pre-commit run --all-files --show-diff-on-failure --color=always

      - name: check that all demos run
        run: cd demos && uv run bash run_all_demos.sh
